#!/usr/bin/env python3
"""
@realDonaldTrump Truth Social → Mastodon Poster
-------------------------------------------------
Reads posts.md and last_post_id.txt (written by monitor.py) and, if a new
post has been detected since the last Mastodon publish, posts it to Mastodon.

The toot contains:
  - The generated post card PNG as the attached image
  - Only hashtags as the toot text (no post body text)

This script is COMPLETELY INDEPENDENT from monitor.py.
It does NOT modify monitor.py, posts.md, or last_post_id.txt.
It maintains its own state file: last_mastodon_post_id.txt

Environment variables required:
  MASTODON_INSTANCE_URL  – Base URL of your Mastodon instance
                           e.g. https://mastodon.social
  MASTODON_ACCESS_TOKEN  – Your bot account's access token
"""

import os
import re
import sys
import requests
from datetime import datetime, timezone

# ── Configuration ──────────────────────────────────────────────────────────────
POSTS_FILE              = "posts.md"
LAST_MONITOR_ID_FILE    = "last_post_id.txt"           # written by monitor.py (read-only here)
LAST_MASTODON_ID_FILE   = "last_mastodon_post_id.txt"  # our own state file
IMAGES_DIR              = "images"

# Toot text: only hashtags (no post body)
TOOT_TEXT = "#TruthSocial #Trump #realDonaldTrump"

# ── Timestamp helper ───────────────────────────────────────────────────────────

def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

# ── State helpers ──────────────────────────────────────────────────────────────

def load_last_mastodon_id() -> str:
    if os.path.exists(LAST_MASTODON_ID_FILE):
        with open(LAST_MASTODON_ID_FILE, "r", encoding="utf-8") as f:
            return f.read().strip()
    return ""


def save_last_mastodon_id(post_id: str) -> None:
    with open(LAST_MASTODON_ID_FILE, "w", encoding="utf-8") as f:
        f.write(post_id)


def load_current_monitor_id() -> str:
    if os.path.exists(LAST_MONITOR_ID_FILE):
        with open(LAST_MONITOR_ID_FILE, "r", encoding="utf-8") as f:
            return f.read().strip()
    return ""

# ── posts.md parser ────────────────────────────────────────────────────────────

def parse_latest_post() -> dict | None:
    """
    Parse posts.md and return the most recent post as a dict.
    Returns None if the file doesn't exist or is empty.
    """
    if not os.path.exists(POSTS_FILE):
        print(f"[{_now()}] {POSTS_FILE} not found – nothing to post.")
        return None

    with open(POSTS_FILE, "r", encoding="utf-8") as f:
        content = f.read()

    if not content.strip():
        print(f"[{_now()}] {POSTS_FILE} is empty – nothing to post.")
        return None

    blocks = re.split(r"(?=\n## Post detected at |\A## Post detected at )", content)
    blocks = [b.strip() for b in blocks if b.strip() and "## Post detected at" in b]

    if not blocks:
        print(f"[{_now()}] No post blocks found in {POSTS_FILE}.")
        return None

    block = blocks[0]   # most recent (newest-first)

    post: dict = {
        "post_id":    "",
        "card_path":  "",   # path to the generated _card.png
        "post_url":   "",
        "created_at": "",
        "fetched_at": "",
    }

    m = re.search(r"## Post detected at (.+)", block)
    if m:
        post["fetched_at"] = m.group(1).strip()

    m = re.search(r"\*\*Post ID:\*\* `([^`]+)`", block)
    if m:
        post["post_id"] = m.group(1).strip()

    m = re.search(r"\*\*Posted on Truth Social:\*\* (.+)", block)
    if m:
        post["created_at"] = m.group(1).strip()

    m = re.search(r"\*\*Source:\*\* \[([^\]]+)\]", block)
    if m:
        post["post_url"] = m.group(1).strip()

    # Look for the card PNG path (generated by monitor.py)
    # Pattern: ![Post card](images/POSTID_card.png)
    m = re.search(r"!\[Post card\]\((images/[^\)]+_card\.png)\)", block)
    if m:
        post["card_path"] = m.group(1).strip()
    else:
        # Fallback: try to find any image path for this post
        if post["post_id"]:
            candidate = os.path.join(IMAGES_DIR, f"{post['post_id']}_card.png")
            if os.path.exists(candidate):
                post["card_path"] = candidate

    return post if post["post_id"] else None

# ── Mastodon API helpers ───────────────────────────────────────────────────────

def _mastodon_headers(token: str) -> dict:
    return {"Authorization": f"Bearer {token}"}


def upload_card_to_mastodon(instance_url: str, token: str, card_path: str) -> str:
    """Upload the post card PNG to Mastodon and return the media attachment ID."""
    if not card_path or not os.path.exists(card_path):
        print(f"[{_now()}] WARNING: Card image not found at '{card_path}' – posting without image.")
        return ""

    with open(card_path, "rb") as f:
        image_data = f.read()

    filename  = os.path.basename(card_path)
    mime_type = "image/png"

    print(f"[{_now()}] Uploading card image: {card_path} ({len(image_data):,} bytes)")

    upload_url = f"{instance_url.rstrip('/')}/api/v2/media"
    try:
        resp = requests.post(
            upload_url,
            headers=_mastodon_headers(token),
            files={"file": (filename, image_data, mime_type)},
            data={"description": "Post from @realDonaldTrump on Truth Social"},
            timeout=60,
        )
        resp.raise_for_status()
        media_id = resp.json().get("id", "")
        print(f"[{_now()}] Card uploaded to Mastodon – media ID: {media_id}")
        return media_id
    except Exception as e:
        print(f"[{_now()}] WARNING: Image upload failed: {e}", file=sys.stderr)
        if hasattr(e, "response") and e.response is not None:
            print(f"[{_now()}] Response: {e.response.text}", file=sys.stderr)
        return ""


def post_to_mastodon(instance_url: str, token: str,
                     toot_text: str, media_id: str) -> bool:
    """Post a status to Mastodon. Returns True on success."""
    status_url = f"{instance_url.rstrip('/')}/api/v1/statuses"
    payload: dict = {"status": toot_text}
    if media_id:
        payload["media_ids[]"] = media_id

    try:
        resp = requests.post(
            status_url,
            headers=_mastodon_headers(token),
            data=payload,
            timeout=30,
        )
        resp.raise_for_status()
        toot_url = resp.json().get("url", "")
        print(f"[{_now()}] ✅ Toot posted successfully: {toot_url}")
        return True
    except Exception as e:
        print(f"[{_now()}] ERROR: Failed to post to Mastodon: {e}", file=sys.stderr)
        if hasattr(e, "response") and e.response is not None:
            print(f"[{_now()}] Response: {e.response.text}", file=sys.stderr)
        return False

# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    print(f"[{_now()}] ── @realDonaldTrump Mastodon Poster starting ──")

    instance_url = os.environ.get("MASTODON_INSTANCE_URL", "").rstrip("/")
    token        = os.environ.get("MASTODON_ACCESS_TOKEN", "")

    if not instance_url or not token:
        print("ERROR: MASTODON_INSTANCE_URL and MASTODON_ACCESS_TOKEN must be set.",
              file=sys.stderr)
        sys.exit(1)

    current_monitor_id = load_current_monitor_id()
    last_mastodon_id   = load_last_mastodon_id()

    print(f"[{_now()}] Monitor's latest post ID : {current_monitor_id or '(none)'}")
    print(f"[{_now()}] Last posted to Mastodon  : {last_mastodon_id  or '(none)'}")

    if not current_monitor_id:
        print(f"[{_now()}] No post recorded by monitor yet – nothing to do.")
        sys.exit(0)

    if current_monitor_id == last_mastodon_id:
        print(f"[{_now()}] Already posted this post to Mastodon – nothing to do.")
        sys.exit(0)

    post = parse_latest_post()
    if not post:
        print(f"[{_now()}] Could not parse a post from {POSTS_FILE} – exiting.")
        sys.exit(0)

    print(f"[{_now()}] New post to publish: {post['post_id']}")
    print(f"[{_now()}] Card path: {post['card_path'] or '(none found)'}")

    # ── Upload the card image ─────────────────────────────────────────────────
    media_id = upload_card_to_mastodon(instance_url, token, post["card_path"])

    # ── Post to Mastodon (hashtags only + card image) ─────────────────────────
    print(f"[{_now()}] Toot text: {TOOT_TEXT!r}")
    success = post_to_mastodon(instance_url, token, TOOT_TEXT, media_id)

    if success:
        save_last_mastodon_id(post["post_id"])
        print(f"[{_now()}] State saved → {LAST_MASTODON_ID_FILE}")
    else:
        print(f"[{_now()}] Post failed – state NOT updated (will retry next run).")
        sys.exit(1)

    print(f"[{_now()}] ── Done ──")


if __name__ == "__main__":
    main()
