#!/usr/bin/env python3
"""
@realDonaldTrump Truth Social → Mastodon Poster
-------------------------------------------------
Reads posts.md and last_mastodon_post_id.txt to determine which posts
have NOT yet been published to Mastodon, then posts ALL of them (oldest
first) so no post is ever skipped.

The toot contains:
  - The generated post card PNG as the attached image
  - Only hashtags as the toot text (no post body text)

This script is COMPLETELY INDEPENDENT from monitor.py.
It does NOT modify monitor.py, posts.md, or last_post_id.txt.
It maintains its own state file: last_mastodon_post_id.txt

Environment variables required:
  MASTODON_INSTANCE_URL  – Base URL of your Mastodon instance
                           e.g. https://mastodon.social
  MASTODON_ACCESS_TOKEN  – Your bot account's access token
"""

import os
import re
import sys
import time
import requests
from datetime import datetime, timezone

# ── Configuration ──────────────────────────────────────────────────────────────
POSTS_FILE              = "posts.md"
LAST_MASTODON_ID_FILE   = "last_mastodon_post_id.txt"  # our own state file
IMAGES_DIR              = "images"

# Toot text: only hashtags (no post body)
TOOT_TEXT = "#TruthSocial #Trump #realDonaldTrump"

# Delay between consecutive toots to avoid Mastodon rate-limits (seconds)
INTER_TOOT_DELAY = 5

# ── Timestamp helper ───────────────────────────────────────────────────────────

def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

# ── State helpers ──────────────────────────────────────────────────────────────

def load_last_mastodon_id() -> str:
    if os.path.exists(LAST_MASTODON_ID_FILE):
        with open(LAST_MASTODON_ID_FILE, "r", encoding="utf-8") as f:
            return f.read().strip()
    return ""


def save_last_mastodon_id(post_id: str) -> None:
    with open(LAST_MASTODON_ID_FILE, "w", encoding="utf-8") as f:
        f.write(post_id)

# ── posts.md parser ────────────────────────────────────────────────────────────

def parse_all_posts() -> list[dict]:
    """
    Parse posts.md and return ALL posts as a list of dicts, newest-first
    (matching the order they appear in the file).
    Returns an empty list if the file doesn't exist or is empty.
    """
    if not os.path.exists(POSTS_FILE):
        print(f"[{_now()}] {POSTS_FILE} not found – nothing to post.")
        return []

    with open(POSTS_FILE, "r", encoding="utf-8") as f:
        content = f.read()

    if not content.strip():
        print(f"[{_now()}] {POSTS_FILE} is empty – nothing to post.")
        return []

    blocks = re.split(r"(?=\n## Post detected at |\A## Post detected at )", content)
    blocks = [b.strip() for b in blocks if b.strip() and "## Post detected at" in b]

    if not blocks:
        print(f"[{_now()}] No post blocks found in {POSTS_FILE}.")
        return []

    posts = []
    for block in blocks:
        post: dict = {
            "post_id":    "",
            "card_path":  "",
            "post_url":   "",
            "created_at": "",
            "fetched_at": "",
        }

        m = re.search(r"## Post detected at (.+)", block)
        if m:
            post["fetched_at"] = m.group(1).strip()

        m = re.search(r"\*\*Post ID:\*\* `([^`]+)`", block)
        if m:
            post["post_id"] = m.group(1).strip()

        m = re.search(r"\*\*Posted on Truth Social:\*\* (.+)", block)
        if m:
            post["created_at"] = m.group(1).strip()

        m = re.search(r"\*\*Source:\*\* \[([^\]]+)\]", block)
        if m:
            post["post_url"] = m.group(1).strip()

        # Look for the card PNG path (generated by monitor.py)
        m = re.search(r"!\[Post card\]\((images/[^\)]+_card\.png)\)", block)
        if m:
            post["card_path"] = m.group(1).strip()
        else:
            if post["post_id"]:
                candidate = os.path.join(IMAGES_DIR, f"{post['post_id']}_card.png")
                if os.path.exists(candidate):
                    post["card_path"] = candidate

        if post["post_id"]:
            posts.append(post)

    return posts  # newest-first (as stored in posts.md)

# ── Mastodon API helpers ───────────────────────────────────────────────────────

def _mastodon_headers(token: str) -> dict:
    return {"Authorization": f"Bearer {token}"}


def upload_card_to_mastodon(instance_url: str, token: str, card_path: str) -> str:
    """Upload the post card PNG to Mastodon and return the media attachment ID."""
    if not card_path or not os.path.exists(card_path):
        print(f"[{_now()}] WARNING: Card image not found at '{card_path}' – posting without image.")
        return ""

    with open(card_path, "rb") as f:
        image_data = f.read()

    filename  = os.path.basename(card_path)
    mime_type = "image/png"

    print(f"[{_now()}] Uploading card image: {card_path} ({len(image_data):,} bytes)")

    upload_url = f"{instance_url.rstrip('/')}/api/v2/media"
    try:
        resp = requests.post(
            upload_url,
            headers=_mastodon_headers(token),
            files={"file": (filename, image_data, mime_type)},
            data={"description": "Post from @realDonaldTrump on Truth Social"},
            timeout=60,
        )
        resp.raise_for_status()
        media_id = resp.json().get("id", "")
        print(f"[{_now()}] Card uploaded to Mastodon – media ID: {media_id}")
        return media_id
    except Exception as e:
        print(f"[{_now()}] WARNING: Image upload failed: {e}", file=sys.stderr)
        if hasattr(e, "response") and e.response is not None:
            print(f"[{_now()}] Response: {e.response.text}", file=sys.stderr)
        return ""


def post_to_mastodon(instance_url: str, token: str,
                     toot_text: str, media_id: str) -> bool:
    """Post a status to Mastodon. Returns True on success."""
    status_url = f"{instance_url.rstrip('/')}/api/v1/statuses"
    payload: dict = {"status": toot_text}
    if media_id:
        payload["media_ids[]"] = media_id

    try:
        resp = requests.post(
            status_url,
            headers=_mastodon_headers(token),
            data=payload,
            timeout=30,
        )
        resp.raise_for_status()
        toot_url = resp.json().get("url", "")
        print(f"[{_now()}] ✅ Toot posted successfully: {toot_url}")
        return True
    except Exception as e:
        print(f"[{_now()}] ERROR: Failed to post to Mastodon: {e}", file=sys.stderr)
        if hasattr(e, "response") and e.response is not None:
            print(f"[{_now()}] Response: {e.response.text}", file=sys.stderr)
        return False

# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    print(f"[{_now()}] ── @realDonaldTrump Mastodon Poster starting ──")

    instance_url = os.environ.get("MASTODON_INSTANCE_URL", "").rstrip("/")
    token        = os.environ.get("MASTODON_ACCESS_TOKEN", "")

    if not instance_url or not token:
        print("ERROR: MASTODON_INSTANCE_URL and MASTODON_ACCESS_TOKEN must be set.",
              file=sys.stderr)
        sys.exit(1)

    last_mastodon_id = load_last_mastodon_id()
    print(f"[{_now()}] Last posted to Mastodon: {last_mastodon_id or '(none)'}")

    # Parse all posts from posts.md (newest-first)
    all_posts = parse_all_posts()
    if not all_posts:
        print(f"[{_now()}] No posts found in {POSTS_FILE} – nothing to do.")
        sys.exit(0)

    print(f"[{_now()}] Total posts in {POSTS_FILE}: {len(all_posts)}")

    # Find posts that haven't been published to Mastodon yet.
    # posts.md is newest-first; we want to publish oldest-first.
    if last_mastodon_id:
        # Find the index of the last posted ID in the list
        known_ids = {p["post_id"] for p in all_posts}
        if last_mastodon_id not in known_ids:
            # The last posted post has already been rotated out of posts.md.
            # All posts currently in the file are newer → publish all of them.
            unpublished = list(reversed(all_posts))  # oldest-first
        else:
            # Collect all posts that appear BEFORE (i.e. newer than) last_mastodon_id
            # in the newest-first list, then reverse to get oldest-first.
            newer = []
            for p in all_posts:
                if p["post_id"] == last_mastodon_id:
                    break
                newer.append(p)
            unpublished = list(reversed(newer))  # oldest-first
    else:
        # Nothing has ever been posted – publish all posts oldest-first
        unpublished = list(reversed(all_posts))

    if not unpublished:
        print(f"[{_now()}] All posts already published to Mastodon – nothing to do.")
        sys.exit(0)

    print(f"[{_now()}] {len(unpublished)} new post(s) to publish (oldest first).")

    # Publish each unpublished post in order (oldest → newest)
    last_successful_id = last_mastodon_id
    for i, post in enumerate(unpublished):
        print(f"[{_now()}] [{i+1}/{len(unpublished)}] Publishing post {post['post_id']}")
        print(f"[{_now()}]   Card path: {post['card_path'] or '(none found)'}")

        media_id = upload_card_to_mastodon(instance_url, token, post["card_path"])

        print(f"[{_now()}]   Toot text: {TOOT_TEXT!r}")
        success = post_to_mastodon(instance_url, token, TOOT_TEXT, media_id)

        if success:
            last_successful_id = post["post_id"]
            save_last_mastodon_id(last_successful_id)
            print(f"[{_now()}]   State saved → {LAST_MASTODON_ID_FILE}")
            # Polite delay between toots to avoid rate-limiting
            if i < len(unpublished) - 1:
                print(f"[{_now()}]   Waiting {INTER_TOOT_DELAY}s before next toot …")
                time.sleep(INTER_TOOT_DELAY)
        else:
            print(f"[{_now()}]   Post failed – stopping here (will retry next run).")
            sys.exit(1)

    print(f"[{_now()}] ── Done: {len(unpublished)} post(s) published ──")


if __name__ == "__main__":
    main()
